# Generated by Django 5.1.3 on 2024-11-11 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('appTheme', models.CharField(max_length=100)),
                ('joinDate', models.DateField(auto_now_add=True)),
                ('reward', models.IntegerField(default=0)),
                ('lastLoginDate', models.DateField(blank=True, null=True)),
                ('trophy', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='media/profile_photos/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mName', models.CharField(max_length=100)),
                ('dueDate', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='missions/')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='mainapp.account')),
            ],
        ),
        migrations.CreateModel(
            name='Preset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presets', to='mainapp.account')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wName', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=10)),
                ('listCategory', models.TextField()),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='mainapp.account')),
            ],
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('in', 'In'), ('out', 'Out')], max_length=3)),
                ('category', models.CharField(max_length=100)),
                ('addDate', models.DateField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='mainapp.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spendMax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('initTarget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=100)),
                ('range', models.CharField(choices=[('1D', '1 Day'), ('1W', '1 Week'), ('1M', '1 Month'), ('1Y', '1 Year')], max_length=2)),
                ('wallet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scope', to='mainapp.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='FixStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('in', 'In'), ('out', 'Out')], max_length=3)),
                ('category', models.CharField(max_length=100)),
                ('frequency', models.CharField(choices=[('1D', '1 Day'), ('1W', '1 Week'), ('1M', '1 Month'), ('1Y', '1 Year')], max_length=2)),
                ('wallet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fix_statements', to='mainapp.wallet')),
            ],
        ),
    ]
