# Generated by Django 5.1.3 on 2024-11-11 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_country'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
    ]
