# Generated by Django 5.1.3 on 2024-11-13 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_wallet_balance'),
        ('mainapp', '0004_delete_country'),
    ]

    operations = [
    ]
