# Generated by Django 5.1.3 on 2024-11-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_merge_0003_remove_wallet_balance_0004_delete_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='preset',
            name='statement',
            field=models.JSONField(default=list),
        ),
    ]
