# Generated by Django 5.1.3 on 2024-11-16 10:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_preset_statement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scope',
            old_name='initTarget',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='scope',
            name='spendMax',
        ),
        migrations.AddField(
            model_name='scope',
            name='type',
            field=models.CharField(choices=[('in', 'In'), ('out', 'Out')], default='out', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_pic',
            field=models.ImageField(default='profile_photos/default.jpg', upload_to='profile_photos/'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='addDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
