# Generated by Django 5.1.3 on 2024-11-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_mission_curamount_delete_fixstatement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scope',
            name='category',
        ),
        migrations.AlterField(
            model_name='mission',
            name='curAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
