# Generated by Django 5.1.3 on 2024-12-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_remove_scope_category_alter_mission_curamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='goal'),
        ),
    ]
