# Generated by Django 5.1.3 on 2024-12-05 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_remove_mission_pic_alter_scope_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scope',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='mainapp.wallet'),
        ),
        migrations.CreateModel(
            name='ProgressionNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('unlocked', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='mainapp.progressionnode')),
            ],
        ),
    ]
